### ISSUE TITLE
Update code to match example

### ISSUE THREAD

**Issue by reillyjodonnell** [vercel/ai-chatbot#137]
The repo for the Next.JS AI Chatbot does not match the code for the demo at https://chat.vercel.ai/ are these intentionally different?

**Comment by wolfpixels** [comment]
+1

**Comment by anhao** [comment]
+1

**Comment by satishnvrn** [comment]
I'm also having the same problem. I do not want any login for the chatbot in home page. But, it is asking to login with github

**Comment by 0x-Legend** [comment]
Yes they are. It adds some additional functionality like rate limiting through upstash, authentication check, saving chats, and more.

The code you see in the demo is a very basic example.

**Comment by Saran33** [comment]
+1

**Comment by vincor1986** [comment]
+1

**Comment by jaredpalmer** [comment]
closed in #190
