### ISSUE TITLE
 Request to Fine-Tune the GPT Model with Latest Vercel Libraries

### ISSUE THREAD

**Issue by IcedMonk** [vercel/ai-chatbot#140]
I was under the impression that this Vercel chatbot might have been trained on Vercel's personal libraries like SWR or Next.js 13.2. However, it seems to be a normal ChatGPT model. I had the idea of using Next.js 13.2 as a companion to create a project with the latest version. Since Next.js 13.2 was released this year in 2023, it would be tremendously helpful if Vercel could fine-tune the GPT model to incorporate knowledge of these latest libraries.

This would greatly benefit users if the chatbot had knowledge of the latest Vercel libraries and frameworks. This would allow bot to provide more accurate and up-to-date information to users seeking assistance with Next.js 13.2 projects.

**Comment by leerob** [comment]
Hey! This isn't trained on our docs, but that would be a nice idea.
