### ISSUE TITLE
Local development: too many redirects

### ISSUE THREAD

**Issue by gouku** [vercel/ai-chatbot#168]
When running this project on local machine I got infinite redirects when authenticate from GitHub:

<img width="952" alt="image" src="https://github.com/vercel-labs/ai-chatbot/assets/9361308/66940c70-c32f-4df5-966a-0948ea5d7936">

My Authorization callback URL has already been set to localhost but it still does not work:

<img width="545" alt="image" src="https://github.com/vercel-labs/ai-chatbot/assets/9361308/2936bc3f-b5a5-46ff-bd63-4550f253009b">

**Comment by bacaxnot** [comment]
same with auth0
