### ISSUE TITLE
Move to Server Actions entirely

### ISSUE THREAD

**Issue by leerob** [vercel/ai-chatbot#187]
Open to community contributions here! Might be some places to remove event handlers in favor of `form`s and server actions.

**Comment by admineral** [comment]
Many thanks for fixing the bugs, really awesome! This motivates me a lot to implement features.

**Comment by athrael-soju** [comment]
Happy to implement an uploader using a vector DB, to allow doc chat. Do you have any preference on which Vector db @leerob?

**Comment by 0x-Legend** [comment]
A little confused here. I thought Server Actions were meant to be for data mutations that update server side state (like updating username) rather than data fetching to client.

**Comment by leerob** [comment]
Moving to Server Actions here isn't about switching to a vector database, just upgrading some of the client-side event handlers here.

**Comment by 0x-Legend** [comment]
Ah ok, I was afraid you were purposing changing the chat api route to a server action.

I’ll see what I can do to help out 🤝

**Comment by leerob** [comment]
https://github.com/vercel/ai-chatbot/pull/253
