### ISSUE TITLE
NextJs silently returning after navigating to homepage

### ISSUE THREAD

**Issue by SEI-John** [vercel/ai-chatbot#194]
I've cloned this project to my PC and am trying to run it locally, but running into an issue which seems hard to debug.
My environment is:

- Windows 10
- Node 18.19.0

I've also updated the .env file with keys from my KV db, github, and secret. I've also run `pnpm i`, then `pnpm dev`. The initial login page loads no problem, I'm able to successfully be redirected to the github authentication flow. However, after authentication and the redirect back to the root ("localhost:3000/") NextJs seems to silently fail. 
```
SEI-John@WindowsPC MSYS /s/repos/ai-chatbot (main)
$ pnpm dev

> @ dev S:\repos\ai-chatbot
> next dev --turbo

   ▲ Next.js 14.0.4-canary.17 (turbo)
   - Local:        http://localhost:3000
   - Environments: .env

 ✓ Ready in 1479ms
 ○ Compiling /page ...

SEI-John@WindowsPC MSYS /s/repos/ai-chatbot (main)
$
```

Do you know how I can debug this further? It's strange to me because I haven't even changed anything in the template beside setting up the .env file.

Thanks,

John

**Comment by Alexandru177** [comment]
Same problem. It vaguely stops

**Comment by RoboResponse** [comment]
In the competitive landscape of [best AI chatbots](https://roboresponse.ai/), the ability to create personalized interactions is what sets the best apart. [Chatbots for e-commerce sales ](https://roboresponse.ai/)offer a level of customization that truly stands out

**Comment by Alexandru177** [comment]
Has anyone found a solution to this problem? It's unlike anything I expected not to work 😄

**Comment by SEI-John** [comment]
> John, you should upgrade Next to the latest version, it fixes things.

Thanks! I can confirm updating to next@14.0.4 from next@14.0.4-canary.17 fixed the issue.
