### ISSUE TITLE
how to disable authentication 

### ISSUE THREAD

**Issue by metadimensions** [vercel/ai-chatbot#223]
i have added the .env file with all the necessary environment variables after running the project it shows this below screen
<img width="1144" alt="Screenshot 2024-01-18 at 8 10 58 PM" src="https://github.com/vercel/ai-chatbot/assets/17061316/c6004d12-8379-4e28-aaf6-4981e8be5304"> 

Also can we add other authentication methods by disabling the Nextjs Auth - like using Firebase auth something similar to that.

**Comment by manhtruongwang** [comment]
Here my implementation, in /auth.ts
`    authorized({ auth }) {
      // No auth
      // return true

      // this ensures there is a logged in user for -every- request
      return !!auth?.user 
    }
`

And in app/api/chat/route.ts

` 
// Comment this to remove userId
const userId = (await auth())?.user.id

  if (!userId) {
    return new Response('Unauthorized', {
      status: 401
    })
  }
  // No auth
  // const userId = (await auth())?.user.id || 'anonymous'
`

It working still but I work love to have an options to disable auth

**Comment by metadimensions** [comment]
Thanks I have replaced the Github signIn through Google Oauth using the same Nextauth.js provider - the auth flow works fine but the `userId` is undefined also it throws an Unauthorised error if I send the message. Let me know if I need to modify something in `auth.ts` for Google?

**Comment by metadimensions** [comment]
Thanks I have replaced the Github signIn through Google Oauth using the same Nextauth.js provider - the auth flow works fine but the `userId` is undefined also it throws an Unauthorised error if I send the message. Let me know if I need to modify something in `auth.ts` for Google?

**Comment by metadimensions** [comment]
Thanks I have replaced the Github signIn through Google Oauth using the same Nextauth.js provider - the auth flow works fine but the `userId` is undefined also it throws an Unauthorised error if I send the message. Let me know if I need to modify something in `auth.ts` for Google?

**Comment by metadimensions** [comment]
@chrisle Thanks... but i dont want to disable the login now... i have set the providers to Google oAuth instead of Github so now it is redirected to the Google signIn page and the auth flow is correct but the `userId` says its undefined...so it throws an unauthorized error from `route.ts` i checked the Nextauth.js doc there is nothing should be added apart from the secret credentials.....

<img width="132" alt="Screenshot 2024-01-24 at 4 53 13 PM" src="https://github.com/vercel/ai-chatbot/assets/17061316/ea891c84-5fa9-4529-ac02-069e851d2c9e">

**Comment by cyberjon** [comment]
in jwt callback change token.id to like this:

`token.id = profile.sub`

**Comment by metadimensions** [comment]
@cyberjon  Thanks, its working now.
