### ISSUE TITLE
Boilerplate runs on vercel deployment but not locally, missing VERCEL_URL

### ISSUE THREAD

**Issue by noahmacca** [vercel/ai-chatbot#235]
I followed the steps on [the page](https://vercel.com/new/noahs-projects-13e80784/templates/next.js/nextjs-ai-chatbot) and in the vercel deployment wizard, and it worked!

But then I clone and try to run locally, pull the vercel env variables, and it won't run (see error message).

<img width="982" alt="image" src="https://github.com/vercel/ai-chatbot/assets/9661785/6c9ad3ba-1767-4cd4-9546-3367335fbe6d">

Indeed the vercel pull doesn't populate this env variable (sets it to ""). I can put localhost:3000 in there, and the page will load, but then the github login doesn't work. Please help!

**Comment by noahmacca** [comment]
I solved it - you can just put in your prod url and it'll work. My downstream issue was because github oauth doesn't work on localhost, so I had to make another and then that worked fine. Hope this helps someone out there!

**Comment by guylepage3** [comment]
@noahmacca can you explain this a bit better? Not sure what you mean by...

>I solved it - you can just put in your prod url and it'll work. My downstream issue was because github oauth doesn't work on localhost, so I had to make another and then that worked fine. Hope this helps someone out there!

Thx
