### ISSUE TITLE
405 on Chat attempt initial setup

### ISSUE THREAD

**Issue by floriansaul** [vercel/ai-chatbot#237]
Initial deployment worked.
Getting 405 now when trying to chat with it.
POST https://nextjs-chat-plum-eta.vercel.app/api/chat 405 (Method Not Allowed)

that request works fine in the tet url https://chat.vercel.ai/chat/

Thanks!

**Comment by jayleverett** [comment]
@floriansaul were you able to solve this?

I'm seeing the same issue.

**Comment by jayleverett** [comment]
Actually I was able to fix by looking at #98. The issue was simply that my OpenAI account wasn't funded.

To fix I needed to:

1. Fund the account
2. Generate a _new_  OpenAI API key (still got the error w/ the old key)
3. Redeploy on Vercel

**Comment by floriansaul** [comment]
Hey that works great. Weird, I mean it should give you a different error message, it seemed to me like you could do something for free. Anyway, that fixes it for me thank you
