### ISSUE TITLE
Demo from Vercel uses "Vercel Auth" vs "NextAuth.js"

### ISSUE THREAD

**Issue by guylepage3** [vercel/ai-chatbot#257]
Just checking in to see if this project is still relevant.

I've noticed that the version linked as "Demo" is a completely different instance and repository than the one linked to for the project.

One uses "Vercel Auth" and the other uses "NextAuth.js".

Two totally different auth providers.

**Comment by amplicity** [comment]
I can shed some light here. This repo used a commit-referenced version of 'auth.js', which inherits from nextauth (and is nextauth's successor). 

I came on here to ask a very similar question -- how can we update to the latest nextauth version within this repo?

When upgrading the auth.js version from anything other than the manually referenced commit, you face numerous issues
