### ISSUE TITLE
How do we upgrade to the latest version of nextauth (or authjs)?

### ISSUE THREAD

**Issue by amplicity** [vercel/ai-chatbot#258]
Title says it all. This repo references a singular commit from nextauth. When upgrading nextauth, or downgrading, we face numerous issues.

Downgrading does not seem to support the structure that this app was built with. Upgrading introduces other issues.

Has anyone managed to upgrade this repo's authjs dependency off of the referenced commit and had success? If so, could you please share your implementation details and how they differ from this repo?

**Comment by leerob** [comment]
Update to Auth.js is happening here -> https://github.com/vercel/ai-chatbot/pull/253
