### ISSUE TITLE
Currently, this app does not work "properly"

### ISSUE THREAD

**Issue by guylepage3** [vercel/ai-chatbot#259]
Currently, this app does not work "properly". The Auth used in the demo is different from that used in the GitHub repository. There are some redirect / callback issues and the app seems to be partially using an experimental version of NextAuth.js v5 and partially using a stable version of v4. As a result it is quite challenging to debug the app in order to get it to run properly.

**Comment by leerob** [comment]
Update to Auth.js is happening here -> https://github.com/vercel/ai-chatbot/pull/253
