### ISSUE TITLE
Cannot run the latest changes nor seed the db.

### ISSUE THREAD

**Issue by Godrules500** [vercel/ai-chatbot#264]
I'm running into a couple of issues running the latest changes

1) When I run pnpm seed, I receive "Error: Cannot find module 'dotenv/config'" because there is no config. I'm not familiar with Postgres, but was something supposed to be checked in or do I need to configure it myself?

2)When running the app with pnpm dev I receive.
```
Error evaluating Node.js code
Error: Failed to load external module C:\AppInstall\Code\React\ai-chatbot-1/./postcss.config.js: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
```

**Comment by jeremyphilemon** [comment]
@Godrules500 

We just updated the template to support user/password authentication. As a result, you will need to set up a KV and Postgres instance. You can follow the steps in the [readme](https://github.com/vercel/ai-chatbot?tab=readme-ov-file#creating-a-kv-database-instance) to set them up!

**Comment by Godrules500** [comment]
Thanks @jeremyphilemon!  I may have missed it, but do y'all have a changelog summary of everything that was updated?

**Comment by jeremyphilemon** [comment]
@Godrules500 

We're working on the change log, will share a summary once it's ready!

**Comment by jeremyphilemon** [comment]
@Godrules500 here's the [change log](https://vercel.com/changelog/next-js-ai-chatbot-2-0)

I'm closing this since the original issue is no longer relevant since we updated the template in response to feedback we received – we've migrated auth data to the kv datastore so there's no need for setting up another posgresql database.
