### ISSUE TITLE
initialMessages doesn't work, code in main branch

### ISSUE THREAD

**Issue by daniloitj** [vercel/ai-chatbot#322]
initialMessages is never used, history of previous messages cannot be displayed.

className is not present in the interface

export interface ChatProps extends React.ComponentProps<'div'> {
  initialMessages?: Message[]
  id?: string
  session?: Session
  missingKeys: string[]
}

export function Chat({ id, className, session, missingKeys }: ChatProps) {

**Comment by logancox** [comment]
#324 Fixed this issue for me.
