### ISSUE TITLE
render is deprecetated

### ISSUE THREAD

**Issue by mrisaacjoy** [vercel/ai-chatbot#323]
/chat/lib/chat/actions.tsx you are importing + using render when is deprecated and not visible anymore on the docs on line 8

**Comment by athrael-soju** [comment]
@mrisaacjoy If you're having issues using ai-3.1 delete your node_modules folder and rebuild/restart your project.

**Comment by mrisaacjoy** [comment]
![image](https://github.com/vercel/ai-chatbot/assets/167074621/03eeddfe-b53b-47df-a00c-b3e421277264)

@athrael-soju what are you talking about? Im saying that the render line on actions.tsx is deprecated, if you look at the docs its not there so why is there a deprecated method in the code

**Comment by athrael-soju** [comment]
@mrisaacjoy it is mentioned in the release notes: https://vercel.com/blog/vercel-ai-sdk-3-1-modelfusion-joins-the-team, so it should be in the docs soon.
