### ISSUE TITLE
huggingface support

### ISSUE THREAD

**Issue by oscarwang22** [vercel/ai-chatbot#338]
Hi,
Recently, I tried to make the platform use models from Huggingface instead of OpenAI. Unfortunately, it did not work as I intended. Could anyone help with how I can modify the template to use huggingface models instead?

**Comment by leerob** [comment]
Hey there, we don't plan to switch this to Hugging Face, but with the AI SDK you can change to any model you want.

https://sdk.vercel.ai/providers/legacy-providers/hugging-face
