### ISSUE TITLE
Feature request for means to store props to inject into system prompt.

### ISSUE THREAD

**Issue by intoxopox** [vercel/ai-chatbot#356]
I think it would be a terrific value-add to provide the means of storing immutable properties, and dynamic getters that could be injected into the system prompt. Basically, just a `${[name-of-prop]}` is fine and even best, so long as there is a formulated place to store those to be initially set one time only or run on the fly where one can specify use server or client and know that things like consts won't be rerun so that injection into the system prompt can only ever happen once. Dates, sorted/shuffled arrays, whatever. Basically, additional system prompt data better stored separately for organizational purposes, bc it involves a calculation, bc it's really long, or what have you.

As it is, code injected into the system prompt gets rerun during conversation. This feels Very wrong. Why have the system prompt be rerun? Perhaps this helps address it: https://github.com/vercel/ai/pull/1825#issue-2333686721

If this seems moot or implementation is painfully obvious, I apologize.

**Comment by intoxopox** [comment]
Been super quiet on both branches. Any updates soon?

**Comment by leerob** [comment]
Hey, thanks for the suggestion! While we don't plan to do this, you could definitely add it in a fork of this repo.
