### ISSUE TITLE
How to handle multistep toll call with streamUI?

### ISSUE THREAD

**Issue by pavlogolovatyy** [vercel/ai-chatbot#357]
Something like in the docs of [AI SDK RSC](https://sdk.vercel.ai/docs/ai-sdk-rsc/multistep-interfaces#function-composition):

User: What's the status of my wife's upcoming flight?
Function: lookupContacts() -> ["John Doe", "Jane Doe"]
Function: lookupBooking("Jane Doe") -> "BA123 confirmed"
Function: lookupFlight("BA123") -> "Flight BA123 is scheduled to depart on 12th December."
Model: Your wife's flight BA123 is confirmed and scheduled to depart on 12th December.

Before refreshing the chat, only the last UI will be visible: lookupFlight.

How to handle all functions return without refreshing the page?

**Comment by athrael-soju** [comment]
This should be able to do something similar, but maybe outdated: https://github.com/vercel-labs/gemini-chatbot

**Comment by iosifnicolae2** [comment]
I'm also interested in a solution to be able to implement chain of thoughts using AI SDK.

**Comment by pavlogolovatyy** [comment]
It seems like the issue might stem from the following lines of code in [prompt-form.tsx](https://github.com/vercel/ai-chatbot/blob/901e4ccec1645a039bb5bbe3239d66d12a694803/components/prompt-form.tsx#L65):
```
const [_, setMessages] = useUIState<typeof AI>()

const responseMessage = await submitUserMessage(value)
setMessages(currentMessages => [...currentMessages, responseMessage])
```
The `submitUserMessage` function is returning a single message rather than an array of messages. Additionally, during refresh, the messages are being fetched from `AIState`.

**Comment by intoxopox** [comment]
@pavlogolovatyy Curious to see if you found a better way.

**Comment by athrael-soju** [comment]
The Competitions API has a single output. You may want to look into the assistants API

**Comment by JokeJason** [comment]
[AI SDK 3.2](https://vercel.com/blog/introducing-vercel-ai-sdk-3-2) has new feature that maybe helpful
