### ISSUE TITLE
When building and using Redis on-premise

### ISSUE THREAD

**Issue by yoshida-git-ai** [vercel/ai-chatbot#361]
Due to the rules of my organisation, I deleted the project on an external management site

Then I built Redis internally

I tried to link the login system with KeyCloak but I haven't been able to achieve it for days

Is it impossible to do that with internal Redis?

Or is there any solution?

I can already chat with the OpenAI APK key but login is not yet implemented

**Comment by leerob** [comment]
Hey there, unfortunately we can't really help out in this instance specific to your fork of the codebase 🙏
