### ISSUE TITLE
I got a blank result

### ISSUE THREAD

**Issue by MiChaelinzo** [vercel/ai-chatbot#375]
<img width="721" alt="Screenshot 2024-06-26 095554" src="https://github.com/vercel/ai-chatbot/assets/68110223/ab9217dd-953a-4887-9f4a-83f976585653">

**Comment by leerob** [comment]
Could you please try again? I cannot reproduce. Thank you!

**Comment by MiChaelinzo** [comment]
> Could you please try again? I cannot reproduce. Thank you!

https://devaide2.vercel.app/ this is the launched app for me. I used https://aka.ms/AIHackathonAPIProxy API and used secret key from Open AI.
