### ISSUE TITLE
where I can find history conversation list

### ISSUE THREAD

**Issue by zhanglianbo35** [vercel/ai-chatbot#39]
where I can find the history conversation list

**Comment by SamiHK** [comment]
+1

**Comment by yuxxeun** [comment]
in here (?)
![image](https://github.com/vercel-labs/ai-chatbot/assets/50067865/e81e6c45-d3cc-459f-90ab-82d9251eeef5)

**Comment by yuxxeun** [comment]
> > in here (?) ![image](https://user-images.githubusercontent.com/50067865/248679243-e81e6c45-d3cc-459f-90ab-82d9251eeef5.png)
> 
> are you deploy it on your local host?

No, this screenshot is from vercel deploying. But on localhost u can do the same thing and show same result, theres any problem that u faced with it?

**Comment by DanielhCarranza** [comment]
I'm facing the same problem, the chat history is not shown in the sidebar only after reloading

**Comment by yuxxeun** [comment]
> 

are you sure you're login with the same your account vercel account? can you give me a clue about it? some screenshot or anything that related with it because everythings working fine on my machine

![image](https://github.com/vercel-labs/ai-chatbot/assets/50067865/5e67594b-615a-4d0b-9494-84f2bae46a33)

**Comment by swyxio** [comment]
the history does not seem to persist properly unlike chatgpt

**Comment by leerob** [comment]
Looked into this. The issue appears to be that you need to reload to see the latest history entry update on localhost. I am able to verify that behavior. There might be an opportunity to make this better, liking missing a `revalidatePath()` when the new entry is created 🙏 But the history _is_ preserved.

**Comment by leerob** [comment]
Ah, related: https://github.com/vercel-labs/ai-chatbot/issues/87
