### ISSUE TITLE
Unexpected stock UI generation

### ISSUE THREAD

**Issue by jb-dev1** [vercel/ai-chatbot#393]
This is a great demo, I recognize the intent to show the capabilities of RSC and streaming UI objects, and has a very specific prompt to generate stock-related UI cards. However, I'm curious about unexpected behavior that I would want to prevent in my own chat app (happy to move this to vercel / ai if better).

Using an unmodified build, input these two prompts in order:

1. "write a memo with a bold header that talks about fun things to do and see in Novi Sad with a numbered list of places to go and a bulleted list of things to bring."

2. "Where are the top places for tourists in Novi Sad?"

Here is the response:

<img width="1107" alt="Screenshot 2024-08-01 at 9 47 04 AM" src="https://github.com/user-attachments/assets/97200f77-7d6c-44e9-b482-a6a9d09dc5f1">

While I recognize the intent with the system prompt and the OpenAI assistants-ish Zod object, do you have a recommendation on how to prevent this when the topic is not about stocks? 

If the answer is to create individual system prompts aka custom agents that respond based on the content (one for doing stock-price related things, one for answering general questions, all within the same dialog), we've got an issue with how the <AI> context provider is built as I don't believe it allows for "multi LLM instantiation" unless that's where experimental_createProviderRegistry comes in.

**Comment by DustinX** [comment]
The demo functionality is to show stock info, along with that streaming UI you see.
When you use this project template for your own app, just comment out those function call options from the settings passed in to the model initialization.

**Comment by jb-dev1** [comment]
Appreciated, wasn't sure if it indicated a problem with the tools implementation in the AI SDK.
