### ISSUE TITLE
Render function not supporting OpenAI Assistants

### ISSUE THREAD

**Issue by rcamp004** [vercel/ai-chatbot#411]
When I replace model name with an OpenAI assistant number the chat falls over. 
I note within the code for: index.d.ts > render there is a comment saying it supports OpenAI assistants. 

`declare function render<TS extends {
    [name: string]: z.Schema;
} = {}, FS extends {
    [name: string]: z.Schema;
} = {}>(options: {
    /**
     * The model name to use. Must be OpenAI SDK compatible. Tools and Functions are only supported
     * GPT models (3.5/4), OpenAI Assistants, Mistral small and large, and Fireworks firefunction-v1.
     *
     * @example "gpt-3.5-turbo"
     */
    model: string;
    /**
     * The provider instance to use. Currently the only provider available is OpenAI.
     * This needs to match the model name.`
I call it with: 
`  const ui = render({
    model: process.env.local.assistant,
    provider: openai,
    initial: <SpinnerMessage />,`

I get a runtime error in terminal: 
status: 404,
  headers: {
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '8be7a5be5e549578-LHR',
    connection: 'keep-alive',
    'content-encoding': 'gzip',
    'content-type': 'application/json; charset=utf-8',
    date: 'Thu, 05 Sep 2024 16:38:03 GMT',
    server: 'cloudflare',
    'set-cookie': '__cf_bm=KvdCEcH8UzKEfyrVBLP.Kf3qlNHcIHytsxYGpd98uOg-1725554283-1.0.1.1-eN0ZPD6TCqAekjSTosh1nelL9CW94bTqriCi3bFwXXa11UujaPFq0jO_MWg2R6K4l89bTk3pAXi1fYdsYcUNrw; path=/; expires=Thu, 05-Sep-24 17:08:03 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=jju7quKYNkPRnzje7EibbCPK1L.q3.VFLdsyn1VbXmk-1725554283397-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
    'strict-transport-security': 'max-age=15552000; includeSubDomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Origin',
    'x-content-type-options': 'nosniff',
    'x-request-id': 'req_fc82c566345863eb8dba10f322c0d760'
  },
  request_id: 'req_fc82c566345863eb8dba10f322c0d760',
  error: {
    message: 'The model `asst_****rQi` does not exist or you do not have access to it.',
    type: 'invalid_request_error',
    param: null,
    code: 'model_not_found'
  },
  code: 'model_not_found',
  param: null,
  type: 'invalid_request_error'
}
NotFoundError: 404 The model `asst_****rQi` does not exist or you do not have access to it.
    at APIError.generate (webpack-internal:///(rsc)/./node_modules/.pnpm/openai@4.57.3_zod@3.22.4/node_modules/openai/error.mjs:69:20)
    at OpenAI.makeStatusError (webpack-internal:///(rsc)/./node_modules/.pnpm/openai@4.57.3_zod@3.22.4/node_modules/openai/core.mjs:304:65)
    at OpenAI.makeRequest (webpack-internal:///(rsc)/./node_modules/.pnpm/openai@4.57.3_zod@3.22.4/node_modules/openai/core.mjs:347:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (webpack-internal:///(rsc)/./node_modules/.pnpm/ai@3.0.21_react@18.2.0_solid-js@1.8.22_svelte@4.2.19_vue@3.5.2_zod@3.22.4/node_modules/ai/rsc/dist/rsc-server.mjs:1076:36) 

I've been stuck on this since March so this is less an issue and more of a request for help.

**Comment by jeremyphilemon** [comment]
Hey @rcamp004, this template uses `streamUI` from the ai sdk, which is not compatible with OpenAI assistants. The `model` field only supports valid language model ids from providers, that's why you're seeing the error.

If you're looking to integrate OpenAI assistants into your application, you will need to use the `useAssistant` hook! You can check out an [example](https://github.com/vercel/ai/blob/main/examples/next-openai-pages/pages/assistants/stream-assistant-response-with-tools/index.tsx) here.
