### ISSUE TITLE
Initial Deployment on Vercel fails due to Postgres, but this should not be required according to description

### ISSUE THREAD

**Issue by ai-fy** [vercel/ai-chatbot#444]
When i start a new project on Vercel with this template, the deployment does end in a failure "Error: POSTGRES_URL is not defined", but a KV-Store should be sufficient to run this template according to the description and setup-wizard.

**Comment by zzh8829** [comment]
the new UI refresh changed the backend from kv to postgres, looks like the readme needs to be updated

**Comment by elijah-io** [comment]
The build steps on Vercel’s Deploy page also need updated.

**Comment by jeremyphilemon** [comment]
Hey guys, the updated template uses Postgres and Blob storage, so their keys are necessary for a successful deploy. I went ahead and updated the readme [here](https://vercel.com/templates/next.js/nextjs-ai-chatbot).

**Comment by elijah-io** [comment]
Thank you so much, this issue can be marked resolved I believe.

**Comment by ai-fy** [comment]
you guys are amazing, thank you very much!

**Comment by ai-fy** [comment]
amazingliy fast fix, great work!
