### ISSUE TITLE
Cannot register new user

### ISSUE THREAD

**Issue by drbarq** [vercel/ai-chatbot#447]
Hello Team, 

I tried to deploy the template - it deploys fine, no errors.  But when I try to register a new user, it says failed to validate settings. The logs show a 200.  

Running locally I find the same behavior and none of the relative paths are resolving.  "Unable to resolve path to module '@/db/queries'."  I have not changed anything within the code base.

Is this user error or is something not working?  I realize there is a new template and didn't know if you are seeing similar issues.  

![Screenshot 2024-10-16 at 5 01 16 PM](https://github.com/user-attachments/assets/d793e997-d25e-4d74-b588-1d9f151fdb42)

In the deployed version I see this error within the console for the deployed version and local. 
background.js:1200 Uncaught (in promise) Error: Failed to get port
    at VJe (background.js:1200:40540)
    at async EKA (background.js:1200:40613)
    
   Any help would be greatly appreciated!
  
Thank you

**Comment by drbarq** [comment]
also the default hosted version with vercel does not work 

https://chat.vercel.ai/login

**Comment by drbarq** [comment]
never mind, the password needs to be 6 letters long 

for anyone else running into this
'String must contain at least 6 character(s)',

**Comment by userima** [comment]
I am getting a message that says "account created successfully" but it doesn't redirect me just like your page. Can you help me?
