### ISSUE TITLE
Failing to signup when running app locally

### ISSUE THREAD

**Issue by chrisg220** [vercel/ai-chatbot#450]
I am seeking help debugging my authentication error for the ai-chatbot template app so that I can login and play with the example chatbot application. However, I'm failing to even create a user via the UI login page.

I followed every step of the README. I renamed `.env.example` to `.env.local` and inserted my private keys for `OPENAI_API_KEY`, `AUTH_SECRET`, `BLOB_READ_WRITE_TOKEN`, and `POSTGRES_URL`.  I have the app running locally on `localhost:3000`. I am trying to sign up by filling in an email address and password. But when I press sign up, I get the following errors in the console.

```
// console output

pnpm dev

> ai-chatbot@0.1.0 dev /Users/christophergonzales/Projects/ai-chatbot
> next dev --turbo

  ▲ Next.js 15.0.0-canary.152 (turbo)
  - Local:        http://localhost:3000
  - Environments: .env.local

 ✓ Starting...
 ✓ Compiled in 271ms
 ✓ Ready in 990ms
 ○ Compiling /register ...
 ✓ Compiled /register in 2.5s
 GET /register 200 in 2776ms
Failed to get user from database
 POST /register 200 in 260ms
```

<img width="1723" alt="Screenshot 2024-10-18 at 6 02 21 PM" src="https://github.com/user-attachments/assets/ca0908a5-c9c4-4580-83a1-184842869dbc">

**Comment by chrisg220** [comment]
I got this to work by manually migrating and building (shown below), and then re-starting the app.

```
tsx db/migrate && next build
```

I believe I followed all the steps correctly in the README, so I expected it to work when I started the app. I just wanted to follow up with my resolution in case: 
1. this is a "missing step" in the README
2. I actually did something out of order, and anyone else who does can learn how to resolve a similar issue for them.

**Comment by zdvman** [comment]
Hi, did you solve the issue? I have the same problem.

**Comment by chrisg220** [comment]
@zdvman Yes my problem was solved. Did you have the same error as me? And did you try running the commands I wrote above? What are you seeing now?

**Comment by huyouare** [comment]
I'm also able to repro this issue upon initial installation.
<img width="808" alt="Screenshot 2024-11-02 at 1 47 19 PM" src="https://github.com/user-attachments/assets/e6653cf9-fb8f-4ea0-9809-f0f742782c7c">

**Comment by sudheer-salavadi** [comment]
🚨 Issue: “Failed to Create Account” During Signup

🔹 Cause:
	•	The app requires a PostgreSQL database, but many of us didn't realize this.
	•	Without a database, user authentication and storage don’t work, leading to this error.

✅ Solution: Install and Set Up PostgreSQL

1. After installing PostgresSQL Open Terminal and connect `psql -U postgres` _(Use **postgres** as the default superuser.)_
2. Initiate your PostgreSQL and create data base e.g. `CREATE DATABASE yourapp_db;`
3. verify it was created `\l`
4. Exit PostgreSQL: `\q`
5. Now Edit .env.local inside your Next.js project and add: POSTGRES_URL=postgres://postgres@localhost:5432/yourapp_db

**Next** 
The database is now created but its empty. So run migrations 
`pnpm tsx lib/db/migrate.ts && pnpm run build`

Then check if tables were created.
`psql -U postgres -d yourapp_db`

then `\dt`

If the database is setup correctly you should see the following tables
```
public | User       | table | postgres
public | Chat       | table | postgres
public | Message    | table | postgres
```
Note: If no tables appear, migrations did not run properly.

That's it, if you spot user table, you are good to go. 

<img width="581" alt="Image" src="https://github.com/user-attachments/assets/91e4f57d-e44d-498e-a39e-0fb68f1cbef6" />

**Comment by karlhorky** [comment]
@sudheer-salavadi nice alternative! I've opened a PR to document setup and usage of local PostgreSQL and `.env.local` files here:

- https://github.com/vercel/ai-chatbot/pull/938
