### ISSUE TITLE
Vercel Deployement: Failed to load resource: the server responded with a status of 500 ()

### ISSUE THREAD

**Issue by alpacaPwaa** [vercel/ai-chatbot#568]
I encountered a 500 Internal Server Error when trying to use the AI chat I deployed on Vercel. Every time I attempt to submit a chat, the server fails to respond correctly, and the following error is displayed in the browser console:

https://ai-chat-azure.vercel.app/api/chat 500 (Internal Server Error)

**Comment by VadzimAlkhimionak** [comment]
@alpacaPwaa how did you solve this issue?

**Comment by alpacaPwaa** [comment]
@VadzimAlkhimionak I made a typo on my open ai env in vercel deployment, I just fixed it and it solves the problem.
