### ISSUE TITLE
Document streaming: Maximum update depth exceeded

### ISSUE THREAD

**Issue by ctjlewis** [vercel/ai-chatbot#639]
Reporting same issue as #589. Actually very hard to debug, can't tell where the loop is coming from or how to break it. The stream gets passed from `useChat()` to `<BlockStreamHandler>` and somewhere along the line it apparently loops. 

![Screenshot 2024-12-18 at 6 05 24 PM](https://github.com/user-attachments/assets/a616d734-6f12-4b3a-9eab-5773b5b7491a)

- It happens whenever you have the document open and it is being written for the first time. I don't know if it happens for edits. 
- If you use `experimental_throttle` in `useChat`, you can avoid it somehow, or the layout doesn't jank - but then chunks are missed (which is confusing, I'd think that would just space the chunks out). 

It is a pretty big issue with the template, and the template/layout is not really stable until this is fixed. I've tried to debug it for a few days but ultimately would be fastest for original authors to find the leak. Aside from that, it's beautiful and I'm shocked this supports documents/canvas now, very helpful. I'm just streaming document output to regular message boxes for now to work around this.

cc @jeremyphilemon

**Comment by MEESKON** [comment]
Agree, please fix. Before this is fixed the template is unusable.

**Comment by athrael-soju** [comment]
@ctjlewis since this is already mentioned here: https://github.com/vercel/ai-chatbot/issues/589 there's no need for a duplicate. Can you please update that one instead?

**Comment by ctjlewis** [comment]
@athrael-soju It's two weeks old, so I intentionally re-raised the issue as a duplicate.

**Comment by jeremyphilemon** [comment]
@ctjlewis thanks for reporting this issue! this should've been fixed in #637 – can you confirm?

**Comment by ctjlewis** [comment]
Let me clone and verify, I'll self-close for you, thanks so much.

**Comment by ctjlewis** [comment]
@jeremyphilemon This is absolutely fixed, just tested deploy flow, really good work.

**Comment by MEESKON** [comment]
Thankyou @jeremyphilemon !!
